ShoppingWebAppMVC/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShoppingWebAppMVC.Models;
using ShoppingWebAppMVC.ViewModel;


namespace ShoppingWebAppMVC.Controllers
{
    public class ItemController : Controller
    {
        ShoppingECartDBEntities db = new ShoppingECartDBEntities();
        public ItemController()
        {

        }
        // GET: Item
        public ActionResult Index()
        {
            ItemViewModel objItemViewModel = new ItemViewModel();
            //A CategorySelectListItems le asignamos valores de CategoryName-CategoryID
            objItemViewModel.CategorySelectListItems = (from d in db.Categories   
                                                        select new SelectListItem() { 
                                                            Text=d.CategoryName,
                                                            Value=d.CategoryID.ToString(),
                                                            Selected=true
                                                        });
            return View(objItemViewModel);
        }
        [HttpPost]
        public JsonResult Index(ItemViewModel objItemViewModel) /*para pasar los datos a la base de datos*/
        {
            string NewImage = Guid.NewGuid() + Path.GetExtension(objItemViewModel.ImagenPath.FileName); /*crea 9a48-614757b6cd53.jfif*/
            objItemViewModel.ImagenPath.SaveAs(Server.MapPath("~/Imagens/" + NewImage)); /*se Guarda la imagen con el nombre de la carpeta a donde se guarda y la ruta*/

            Items objItem = new Items(); /*creo un objeto de la tabla items. para pasarle los valores de objItemViewModel*/
            objItem.ImagenPath = "~/Imagens/" + NewImage; /*se le pasa el acceso y el nombre de la ruta*/
            objItem.CategoryID = objItemViewModel.CategoryID;
            objItem.Description = objItemViewModel.Description;
            objItem.ItemCode = objItemViewModel.ItemCode;
            objItem.ItemID = Guid.NewGuid(); /*Representa un identificador único global*/
            objItem.ItemName = objItemViewModel.ItemName;
            objItem.ItemPrice = objItemViewModel.ItemPrice;
            db.Items.Add(objItem); /*agregamos objItem a la tabla items*/
            db.SaveChanges();

            return Json(new { success = true, Message = "Compra Guardada con Exito" }, JsonRequestBehavior.AllowGet);
        }
    } 
}

ShoppingWebAppMVC/Controllers/ShoppingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShoppingWebAppMVC.Models;
using ShoppingWebAppMVC.ViewModel;

namespace ShoppingWebAppMVC.Controllers
{
    public class ShoppingController : Controller
    {
        ShoppingECartDBEntities db = new ShoppingECartDBEntities();
        List<ShoppingCartViewModel> listOfShoppingCartViewModel = new List<ShoppingCartViewModel>(); /*a la clase la hago una lista*/
        // GET: Shopping
        public ActionResult Index()
        {
            //Lista de ShoppingViewModel Igualando valores de las dos tablas para ser ultilizados
            //se cita a objetos de las dos tablas para poder asignarle valor a los valores de ShoppingViewModel.
            IEnumerable<ShoppingViewModel> listOfShoppingViewModel = (from d in db.Items
                                                                      join
                                                                      dbCat in db.Categories
                                                                      on d.CategoryID equals dbCat.CategoryID
                                                                      select new ShoppingViewModel()
                                                                      {
                                                                          ImagenPath = d.ImagenPath,
                                                                          ItemID = d.ItemID,
                                                                          ItemName = d.ItemName,
                                                                          ItemCode = d.ItemCode,
                                                                          Description = d.Description,
                                                                          ItemPrice = d.ItemPrice,
                                                                          Category = dbCat.CategoryName,
                                                                      }).ToList();


            return View(listOfShoppingViewModel);
        }
        [HttpPost]
        public JsonResult Index(string ItemID)
        {
            //creo un obj de ShoppingCartViewModel 
            ShoppingCartViewModel objShoppCart = new ShoppingCartViewModel();

            //este objItem almaceno la coincidencia del ItemID de la tabla Item y ItemId de 
            Items objItem = db.Items.Single(model => model.ItemID.ToString() == ItemID);
            if (Session["CartCount"] != null)
            {
                //agrega a la cart un elemento mas
                listOfShoppingCartViewModel = Session["ItemCart"] as List<ShoppingCartViewModel>;
            }
            if (listOfShoppingCartViewModel.Any(model => model.ItemID == ItemID))
            {

                objShoppCart = listOfShoppingCartViewModel.Single(model => model.ItemID == ItemID);
                objShoppCart.Quantity = objShoppCart.Quantity + 1;
                objShoppCart.Total = objShoppCart.Quantity * objShoppCart.UnitPrice;
            }
            else
            {
                objShoppCart.ItemID = ItemID;
                objShoppCart.ImagenPath = objItem.ImagenPath;
                objShoppCart.ItemName = objItem.ItemName;
                objShoppCart.Quantity = +1;
                objShoppCart.UnitPrice = objItem.ItemPrice;
                objShoppCart.Total = objItem.ItemPrice;
                //Agrego estos nuevo datos a los parametros de ShoppingCartViewModel
                listOfShoppingCartViewModel.Add(objShoppCart);
            }
            //para guardar datos en memoria hasta cerrar la sesion
            Session["CartCount"] = listOfShoppingCartViewModel.Count;
            Session["ItemCart"] = listOfShoppingCartViewModel;
            return Json(new { Success = true, Counter = listOfShoppingCartViewModel.Count }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult ShoppingCart() /*Creo una vista para Cart y hacer una lista de los productos agregados*/
        {
            
            listOfShoppingCartViewModel = Session["ItemCart"] as List<ShoppingCartViewModel>;
            return View(listOfShoppingCartViewModel);
        }

        [HttpPost]
        public ActionResult SaveOrder()
        {
            int OrderId = 0;
            listOfShoppingCartViewModel = Session["ItemCart"] as List<ShoppingCartViewModel>;
            Orders objOrder = new Orders()
            {
                OrderDate = DateTime.Now,
                OrderNumber=String.Format("{0:ddmmyyyyHHmmss}",DateTime.Now)
            };
            db.Orders.Add(objOrder);
            db.SaveChanges();

            //le asigno valor a la variable int OrderId..para usarlo en el foreach
            OrderId = objOrder.OrderId;
            foreach (var item in listOfShoppingCartViewModel)
            {
                OrderDetails objOrderDetail = new OrderDetails();
                objOrderDetail.OrderId = OrderId;
                objOrderDetail.Quantity = item.Quantity;
                objOrderDetail.ItemId = item.ItemID;
                objOrderDetail.UnitPrice = item.UnitPrice;
                objOrderDetail.Total = item.Total;
                db.OrderDetails.Add(objOrderDetail);
                db.SaveChanges();
            }
            Session["ItemCart"] = null;
            Session["CartCount"] = null;
            return RedirectToAction("Index");
        }
    }
}

    

ShoppingWebAppMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Shopping</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery-1.8.0.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Ecommer Card", "Index", "Shopping", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Add Products", "Index", "Item")</li>
                </ul>
                    @Html.Partial("_ShoppingCart")
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

ShoppingWebAppMVC/Views/Shared/_ShoppingCart.cshtml
@*vista parcial creada para mostrar en el navbar la cantidad de productos en la cart*@
<ul class="nav navbar-nav navbar-right">
    <li>
        @if (Session["CartCount"] == null)
        {
            @Html.ActionLink("Cart", "ShoppingCart", "Shopping", new { id = "ItemCart" })
        }
        else
        {
            @Html.ActionLink("Cart   "+Session["CartCount"], "ShoppingCart", "Shopping", new { id = "ItemCart" })
        }
    </li>
</ul>